// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQ-9Wca5JhQAK1r2Sm2m5DlVGbSaiq2c',
    appId: '1:463124726401:android:3f1fdaf147de3607854380',
    messagingSenderId: '463124726401',
    projectId: 'bikeset-68364',
    databaseURL: 'https://bikeset-68364.firebaseio.com',
    storageBucket: 'bikeset-68364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawzIO4-qRKsr74iqKcmrZ8UrnAmtx_Vw',
    appId: '1:463124726401:ios:61cead0919a9ec5e854380',
    messagingSenderId: '463124726401',
    projectId: 'bikeset-68364',
    databaseURL: 'https://bikeset-68364.firebaseio.com',
    storageBucket: 'bikeset-68364.appspot.com',
    androidClientId: '463124726401-ctmi5q4ac64d5bk6vnrcosjdpuunnk7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundPushNotification',
  );
}
